declare class Chat {
    static readonly AJAX_LOGIN_ADDRESS: string;
    static readonly WEB_SOCKETS_ADDRESS: string;
    protected static: typeof Chat;
    private _development;
    private _id;
    private _user;
    private _socket;
    private _loginForm;
    private _loginUserElm;
    private _loginPassElm;
    private _logoutBtn;
    private _chatRoom;
    private _currentUser;
    private _onlineUsers;
    private _messages;
    private _messageForm;
    private _recepientsElms;
    private _messageElm;
    private _recepients;
    private _audioElm;
    private _typingUsersCont;
    private _typingUsers;
    constructor();
    private _initElements;
    private _initElementRecepients;
    private _initEvents;
    private _initAutoLogin;
    private _initAutoLoginDevelopment;
    private _handleClientLoginFormSubmit;
    private _initChatRoom;
    private _initChatRoomElements;
    private _initChatRoomEvents;
    private _handleClientMessageFormSubmit;
    private _handleClientMessageFormTyping;
    private _handleServerUserLogin;
    private _handleServerUserLogout;
    private _handleServerUserTyping;
    private _updateOnlineUsers;
    private _updateRecepients;
    private _addMessage;
    private _getRecepient;
    private _getLoginUrl;
    private _scrollToBottom;
}
//# sourceMappingURL=client.d.ts.map